// Approved job-title library for Senpex / Pckup — a technology-enabled
// last-mile-delivery company. Deliberately streamlined: at most three
// hierarchy levels per operational family (Specialist → Manager → Director)
// and no redundant variations describing the same work.

export const TITLE_LIBRARY = [
  { dept: "Executive & Leadership", titles: [
    "Chief Executive Officer", "Chief Operating Officer", "Chief Technology Officer",
    "Chief Product Officer", "Chief Financial Officer", "Chief Revenue Officer",
    "Chief Marketing Officer", "Chief People Officer", "Chief Strategy Officer",
    "President", "General Manager",
    "Vice President of Operations", "Vice President of Engineering", "Vice President of Product",
    "Vice President of Sales", "Vice President of Partnerships", "Vice President of Customer Experience",
    "Vice President of Finance", "Vice President of People",
    "Head of Operations", "Head of Engineering", "Head of Product", "Head of Sales",
    "Head of Partnerships", "Head of Customer Experience", "Head of Data",
    "Head of Finance", "Head of People",
  ] },
  { dept: "Dispatch & Delivery Operations", titles: [
    "Dispatch Fleet Specialist", "Dispatch Fleet Manager", "Director of Dispatch Operations",
    "Delivery Operations Specialist", "Delivery Operations Manager", "Director of Delivery Operations",
    "Logistics Operations Specialist", "Logistics Operations Manager", "Director of Logistics Operations",
    "Route Operations Specialist", "Route Operations Manager",
    "Delivery Network Manager", "Delivery Capacity Manager", "Delivery Performance Manager",
    "Operations Control Manager",
  ] },
  { dept: "Driver Support", titles: [
    "Driver Experience Specialist", "Driver Experience Manager",
    "Driver Success Specialist", "Driver Success Manager",
    "Driver Engagement Specialist", "Driver Engagement Manager",
    "Driver Acquisition Specialist", "Driver Acquisition Manager",
    "Driver Onboarding Specialist", "Driver Onboarding Manager",
    "Driver Compliance Specialist", "Driver Compliance Manager",
  ] },
  { dept: "Customer Operations & Support", titles: [
    "Customer Experience Specialist", "Customer Experience Manager", "Director of Customer Experience",
    "Customer Support Specialist", "Customer Support Manager", "Director of Customer Support",
    "Client Success Specialist", "Client Success Manager", "Director of Client Success",
    "Enterprise Client Success Manager", "Strategic Account Manager", "Enterprise Account Manager",
    "Customer Operations Specialist", "Customer Operations Manager",
    "Service Delivery Specialist", "Service Delivery Manager",
    "Escalations Specialist", "Escalations Manager", "Customer Quality Manager",
  ] },
  { dept: "Engineering & Technology", titles: [
    "Software Engineer", "Senior Software Engineer", "Staff Software Engineer", "Principal Software Engineer",
    "Backend Engineer", "Frontend Engineer", "Full-Stack Engineer", "Mobile Engineer",
    "iOS Engineer", "Android Engineer", "React Native Engineer",
    "Platform Engineer", "Infrastructure Engineer", "Cloud Engineer", "DevOps Engineer",
    "Site Reliability Engineer", "Solutions Engineer", "Integration Engineer", "API Engineer",
    "Systems Engineer", "Security Engineer", "Application Security Engineer",
    "Quality Assurance Engineer", "QA Automation Engineer", "Test Engineer",
    "Technical Lead", "Engineering Manager", "Director of Engineering",
    "Solutions Architect", "Cloud Architect", "Technical Program Manager", "Release Manager",
    "Database Administrator", "Systems Administrator", "IT Support Specialist", "IT Manager",
  ] },
  { dept: "Data, AI & Optimization", titles: [
    "Data Analyst", "Business Intelligence Analyst", "Operations Analyst", "Logistics Analyst",
    "Delivery Performance Analyst", "Data Engineer", "Analytics Engineer",
    "Machine Learning Engineer", "Artificial Intelligence Engineer", "Applied AI Engineer",
    "MLOps Engineer", "Data Scientist", "Operations Research Scientist",
    "Optimization Engineer", "Route Optimization Engineer", "Geospatial Data Scientist",
    "Forecasting Analyst", "Decision Science Analyst", "Business Intelligence Engineer",
    "Data Platform Engineer", "Data Product Manager", "Analytics Manager", "Data Science Manager",
    "Director of Data", "Director of Artificial Intelligence",
    "Head of Artificial Intelligence",
  ] },
  { dept: "Product, Design & Research", titles: [
    "Product Manager", "Senior Product Manager", "Technical Product Manager",
    "Platform Product Manager", "Operations Product Manager", "Logistics Product Manager",
    "Growth Product Manager", "Group Product Manager", "Director of Product",
    "Product Operations Specialist", "Product Operations Manager", "Product Analyst",
    "Product Designer", "Senior Product Designer", "User Experience Designer",
    "User Interface Designer", "UX Researcher", "Design Systems Designer",
    "Graphic Designer", "Creative Designer", "Design Lead", "Design Manager", "Director of Design",
  ] },
  { dept: "Sales, Partnerships & Business Development", titles: [
    "Sales Development Representative", "Business Development Representative",
    "Account Executive", "Senior Account Executive", "Enterprise Account Executive",
    "Strategic Account Executive", "Sales Manager", "Enterprise Sales Manager", "Director of Sales",
    "Business Development Manager", "Director of Business Development",
    "Strategic Partnerships Manager", "Enterprise Partnerships Manager",
    "Technology Partnerships Manager", "Channel Partnerships Manager", "Director of Partnerships",
    "Solutions Consultant", "Sales Engineer",
    "Revenue Operations Specialist", "Revenue Operations Manager", "Director of Revenue Operations",
    "Commercial Operations Manager", "Proposal Manager",
  ] },
  { dept: "Marketing & Growth", titles: [
    "Marketing Coordinator", "Marketing Specialist", "Growth Marketing Specialist",
    "Growth Marketing Manager", "Performance Marketing Manager", "Digital Marketing Manager",
    "Product Marketing Manager", "Content Marketing Manager", "Brand Marketing Manager",
    "Lifecycle Marketing Manager", "Demand Generation Manager",
    "Search Engine Marketing Specialist", "Search Engine Optimization Specialist",
    "Social Media Manager", "Communications Manager", "Public Relations Manager",
    "Community Manager", "Growth Manager", "Head of Growth", "Director of Marketing",
    "Vice President of Marketing",
  ] },
  { dept: "Finance, Legal & Administration", titles: [
    "Finance Analyst", "Senior Finance Analyst", "Financial Planning and Analysis Manager",
    "Accounting Specialist", "Staff Accountant", "Senior Accountant", "Accounting Manager",
    "Controller", "Director of Finance",
    "Billing Specialist", "Accounts Receivable Specialist", "Accounts Payable Specialist",
    "Payroll Specialist", "Legal Operations Specialist", "Legal Operations Manager",
    "Corporate Counsel", "General Counsel", "Compliance Specialist", "Compliance Manager",
    "Risk Analyst", "Risk Manager", "Fraud Operations Specialist", "Fraud Operations Manager",
    "Insurance and Claims Specialist", "Claims Manager",
    "Procurement Specialist", "Procurement Manager",
    "Office Manager", "Executive Assistant", "Administrative Coordinator",
  ] },
  { dept: "People & Recruiting", titles: [
    "People Operations Specialist", "People Operations Manager",
    "Human Resources Specialist", "Human Resources Manager",
    "Talent Acquisition Specialist", "Talent Acquisition Manager",
    "Technical Recruiter", "Operations Recruiter", "Recruiting Coordinator",
    "Employee Experience Specialist", "Employee Experience Manager",
    "Learning and Development Specialist", "Learning and Development Manager",
    "People Partner", "Director of People",
  ] },
  { dept: "Safety, Compliance & Quality", titles: [
    "Safety Operations Specialist", "Safety Operations Manager",
    "Fleet Safety Specialist", "Fleet Safety Manager", "Delivery Safety Manager",
    "Trust and Safety Specialist", "Trust and Safety Manager",
    "Regulatory Compliance Specialist", "Regulatory Compliance Manager",
    "Courier Compliance Specialist", "Courier Compliance Manager",
    "Quality Operations Specialist", "Quality Operations Manager",
    "Service Quality Manager", "Delivery Quality Manager",
    "Incident Response Specialist", "Incident Response Manager",
    "Loss Prevention Specialist", "Loss Prevention Manager",
  ] },
];

// Flat lowercase set for fast server-side membership checks.
export const APPROVED_TITLES = new Set(
  TITLE_LIBRARY.flatMap((g) => g.titles).map((t) => t.toLowerCase())
);
